### ISSUE TITLE
Google Play Store Time-Out on 0.9.1, 0.9.3

### ISSUE THREAD

**Issue by noobww** [trojan-gfw/igniter#215]
Checked:
Igniter works fine with other apps.

Tried:
1. Deleting Play Store Data.
2. Switching off app exemption and cert verification.
3. Reboot.
4. Clearing Play Service cache.
5. Uninstall igniter and reinstall.

No use.

resolv.conf is not found (no such file in /etc/)

**Comment by wongsyrone** [comment]
Uninstall igniter and reinstall

**Comment by noobww** [comment]
> Uninstall igniter and reinstall

did so, no use

**Comment by TchaikovDriver** [comment]
Sometimes this problem occurred in my phones. I guess the problem is related to VPN service provider. In different periods and with different server, behaviors varied. For sometime in the past, I was not able to use Google Play. But recently, the VPN service provider has released a new list of servers, I tried and found it works. So I think this might not be a bug of Igniter.

**Comment by noobww** [comment]
Update:
Used some alternative and successfully logged into Play Store (with all its data cleared).
The following network data interchange with Igniter has been successful.

Doubt the only problem was sth. about google identifying user?

**Comment by TchaikovDriver** [comment]
> Update:
> Used some alternative and successfully logged into Play Store (with all its data cleared).
> The following network data interchange with Igniter has been successful.
> 
> Doubt the only problem was sth. about google identifying user?

No idea. At least it proves that Igniter works as expected.
