### ISSUE TITLE
crash about server list [0.9.4-beta]

### ISSUE THREAD

**Issue by oasiscifr** [trojan-gfw/igniter#217]
```
Today, 9:03 AM on app version 210000904
Redmi Redmi K20 Pro (raphael), 5632MB RAM, Android 10
Report 1 of 4

java.lang.NullPointerException: 
  at io.github.trojan_gfw.igniter.servers.data.ServerListDataManager.saveServerConfig (ServerListDataManager.java:38)
  at io.github.trojan_gfw.igniter.servers.presenter.ServerListPresenter$2.onRun (ServerListPresenter.java:122)
  at io.github.trojan_gfw.igniter.common.os.Task.run (Task.java:29)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
```

**Comment by TchaikovDriver** [comment]
That's weird. The exception is thrown in `ServerListDataManager#saveServerConfig(TrojanConfig)`:
```java
@Override
public void saveServerConfig(TrojanConfig config) {
    boolean configRemoteAddrExists = false;
    List<TrojanConfig> trojanConfigs = loadServerConfigList();
    for (int i = trojanConfigs.size() - 1; i >= 0; i--) {
        if (trojanConfigs.get(i).getRemoteAddr().equals(config.getRemoteAddr())) {
            trojanConfigs.set(i, config);
            configRemoteAddrExists = true;
            break;
        }
    }
    if (!configRemoteAddrExists) {
        trojanConfigs.add(config);
    }
    replaceServerConfigs(trojanConfigs);
}
```
Here is line 38 in `ServerListDataManager`: 
`if (trojanConfigs.get(i).getRemoteAddr().equals(config.getRemoteAddr())) {`
`NullPointerException` might be caused by `trojanConfigs.get(i)`， `trojanConfigs.get(i).getRemoteAddr()`, `trojanConfigs.get(i).getRemoteAddr().equals()` or `config.getRemoteAddr()` . 

Inferred from `ServerListDataManager#loadServerConfigList()`, `trojanConfigs` must be not null. 
Also, in `TrojanHelper#readTrojanServerConfigList(String)`, where items of `trojanConfigs` are read, it's guaranteed to be not null. 
As for `config`, we have validated it before saving. So, the exception can only be thrown in `trojanConfigs.get(i).getRemoteAddr().equals()`, which means user saved a `TrojanConfig` with null remoteAddr before. But it seems to be impossible for user to save a `TrojanConfig` with empty remoteAddr and pass the validation.

**Comment by oasiscifr** [comment]
Weird. I noticed that all eight related reports today are from the same device.

**Comment by TchaikovDriver** [comment]
I will do some null checking to avoid the exception.

**Comment by TchaikovDriver** [comment]
#222
