### ISSUE TITLE
Please don't set the default input focus in any text box

### ISSUE THREAD

**Issue by dotAge** [trojan-gfw/igniter#218]
The IME is always popped up and covered half screen when I launch the app each time. Users usually never change the connection information once it setup Ok. Thanks!

**Comment by TchaikovDriver** [comment]
Try the debug apk [here](https://github.com/TchaikovDriver/igniter/releases/download/0.9.5-beta/io.github.trojan_gfw.igniter-v0.9.5-beta-SNAPSHOT-210000905-debug.apk).
This is a debug apk with different applicationId from the release apk, which means 2 Igniters will coexist in your phone. Let me know if the problem is solved.

**Comment by dotAge** [comment]
The debug version works well, thanks a lot!
