### ISSUE TITLE
防火牆可通過識別TLS Client Cipher suites識別Trojan/V2Ray TLS

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#230]
https://github.com/v2ray/discussion/issues/704
最近V2Ray TLS和Ingiter被限速了。不清楚Igniter的TLS Cipher suites是什麼。希望Igniter的TLS Client Cipher suites不要有明顯特徵。另外App如果不調用AArch64 AES指令集，會導致AES計算（尤其是AES-GCM）速度緩慢，穩定性差，非常耗電。

**Comment by oasiscifr** [comment]
https://github.com/trojan-gfw/trojan/issues/441
No

**Comment by dbshch** [comment]
The problem actually "exists" in trojan.
The cipher suite in trojan relies on the user's config. So the problem is about the users and the [sample configs](https://trojan-gfw.github.io/trojan/config). I think most users would **just directly use the cipher suite in the examples. That causes the problem.**

As an example, when enabling TLS 1.3, the first problem is the default cipher suite the server used in the sample configs (which is the first of "cipher_tls13" if i'm right) is TLS_AES_128_GCM_SHA256 (in server hello), which i think is rarely used. All common websites with TLS 1.3 prefer TLS_AES_256_GCM_SHA384.
Also the hard coded cipher suite problem in v2ray also exists if the users don't change these configs in example configs.
These two problems (andy maybe other problems in the handshakes) can be easily used to identify the data.

The IND-CCA security based on TLS scheme won't ensure the security of the TLS headers' identification (since these are plaintext, obviously).

A easy and simple way for users to mitigate that is changing these config by ourselve. But I think it would be better to modify the wiki's document and example configs.
1. Users should be WARNED or recommended to change these configurations.
2. The default cipher suite in examples should be modified to simulate the common browsers and websites.
3. Maybe write a tool that generates random configurations for the first run?

But I think there's no way to totally obscure the data when you are connecting to a foreign and uncommon domain for a long time and transmitted huge amount of encrypted data with uncommonly used TLS 1.3 (if enabled). Maybe the above efforts are not necessary.
