### ISSUE TITLE
Why requesting storage permission

### ISSUE THREAD

**Issue by baraja** [trojan-gfw/igniter#244]
V0.9.4: application filter won't work with out storage permission
V0.9.5: storage permission is not forced any more, while app filter won't work without the permission

My point is it shouldn't request storage permission and it should enable the filter function
PS: wording needs to be improved, as users don't know the filter works as a blacklist or a whitelist

**Comment by GreaterFire** [comment]
@baraja See the source code for yourself.

**Comment by baraja** [comment]
Storage permission is not necessary in my opinion, none of the famous fanqiang software would do that...
And it is a bug obviously in v0.9.5, yes you don't request permission any more, but the fuction stopped working

**Comment by TchaikovDriver** [comment]
At the first time the configuration file was stored in private storage. In the early days, Igniter was released frequently and reinstalling was required for updating. Configuration file was removed everytime user uninstalled Igniter. It was quite annoying setting  exempt application list over and over again. So I migrate the file to external storage, which requires WRITE_EXTERNAL_STORAGE_PERMISSION. In the newest release, we migrate it to internal storage again, because uinstalling is not required for updating anymore.
For the issue you encountered, use the previous release and just ignore v0.9.5.
