### ISSUE TITLE
Feature：Need PAC support

### ISSUE THREAD

**Issue by davidanger** [trojan-gfw/igniter#34]
If this can support PAC or custom routing path set, it will be great.

**Comment by oasiscifr** [comment]
There is no plan to support PAC since Android doesn't provide the API to apply PAC for system.

However bypass&routing support is working in progress: https://github.com/trojan-gfw/igniter/pull/29
You can try the unofficial test release: https://github.com/oasiscifr/igniter/releases and modify the clash configuration by yourself.
